services:
  vert:
    container_name: vert
    image: ghcr.io/vert-sh/vert:latest
    environment:
      - PUB_HOSTNAME=${PUB_HOSTNAME:-vert.int.saphnet.xyz}
      - PUB_PLAUSIBLE_URL=${PUB_PLAUSIBLE_URL:-https://plausible.example.com}
      - PUB_ENV=${PUB_ENV:-production}
      - PORT=${PORT:-3000}
      - PUB_VERTD_URL=${PUB_VERTD_URL:-https://vertd.int.saphnet.xyz}
    restart: unless-stopped
    networks:
      - web_bridge

networks:
  web_bridge:
    name: web_bridge
