services:
  foldingathome:
    image: lscr.io/linuxserver/foldingathome:latest
    container_name: foldingathome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - MACHINE_NAME=debian-docker-vm-main
      - CLI_ARGS= #optional
      # Secrets to set in environment:
      - ACCOUNT_TOKEN=$ACCOUNT_TOKEN
    volumes:
      - foldingathome:/config
    ports:
      - 7396:7396 #optional
    devices:
      - /dev/dri/:/dev/dri/
    deploy:
      resources:
        limits:
          cpus: '3.2'
    restart: unless-stopped

volumes:
  foldingathome: