services:
  docker-volume-rclone:
    image: ghcr.io/anarchobooleanism/docker-volume-rclone@sha256:f477a83b3a045a90c1bdcf909f545027b8cfbe7068c169d2e352652f5ab72dcd
    environment:
      - TARGET_SUBDIR_NAME=docker-main-pve3
      - RUN_ON_STARTUP=FALSE
      - CRON_ARGUMENTS=30 * * * * # The 30th minute of every hour
      # - RCLONE_OPTIONS=
      - TZ=America/Los_Angeles
    volumes:
      - deluge-seedbox_deluge-config:/volumes/deluge-seedbox_deluge-config:ro
      - deluge-seedbox_sftp-config:/volumes/deluge-seedbox_sftp-config:ro
      - foldingathome_foldingathome:/volumes/foldingathome_foldingathome:ro
      - media-server_jackett-config:/volumes/media-server_jackett-config:ro
      - media-server_jellyfin-config:/volumes/media-server_jellyfin-config:ro
      - media-server_radarr-config:/volumes/media-server_radarr-config:ro
      - nfs-target:/volumes-clone

volumes:
  deluge-seedbox_deluge-config: # Intentionally ignoring seedbox-files
    external: true
  deluge-seedbox_sftp-config:
    external: true
  foldingathome_foldingathome:
    external: true
  media-server_jackett-config: # Intentionally ignoring jellyfin-cache, media-server-movies
    external: true
  media-server_jellyfin-config:
    external: true
  media-server_radarr-config:
    external: true
  nfs-target:
    driver_opts:
      type: "nfs"
      o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
      device: ":/mnt/saphnet-nas1b/docker-volumes"