services:
  docker-volume-rclone:
    image: ghcr.io/anarchobooleanism/docker-volume-rclone:main
    environment:
      - TARGET_SUBDIR_NAME=docker-portainer
      - RUN_ON_STARTUP=FALSE
      - CRON_ARGUMENTS=30 * * * * # The 30th minute of every hour
      # - RCLONE_OPTIONS=
      - TZ=America/Los_Angeles
    volumes:
      - portainer-server_portainer_data:/volumes/portainer-server_portainer_data:ro
      - nfs-target:/volumes-clone

volumes:
  portainer-server_portainer_data:
    external: true
  nfs-target:
    driver_opts:
      type: "nfs"
      o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
      device: ":/mnt/saphnet-nas1b/docker-volumes"