services:
  docker-volume-rclone:
    image: ghcr.io/anarchobooleanism/docker-volume-rclone:main
    environment:
      - TARGET_SUBDIR_NAME=docker-nginx
      - RUN_ON_STARTUP=FALSE
      - CRON_ARGUMENTS=30 * * * * # The 30th minute of every hour
      # - RCLONE_OPTIONS=
      - TZ=America/Los_Angeles
    volumes:
      - portainer-server_portainer_data:/volumes/portainer-server_portainer_data:ro
      - guacamole-guac-db-data:/volumes/guacamole-guac-db-data:ro
      - nginx-proxy-manager_mysql:/volumes/nginx-proxy-manager_mysql:ro
      - nginx-proxy-manager_letsencrypt:/volumes/nginx-proxy-manager_letsencrypt:ro
      - nginx-proxy-manager_data:/volumes/nginx-proxy-manager_data:ro
      - nfs-target:/volumes-clone

volumes:
  filestash_filestash:
    external: true
  guacamole-guac-db-data:
    external: true
  nginx-proxy-manager_mysql:
    external: true
  nginx-proxy-manager_letsencrypt:
    external: true
  nginx-proxy-manager_data:
    external: true
  nfs-target:
    driver_opts:
      type: "nfs"
      o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
      device: ":/mnt/saphnet-nas1b/docker-volumes"